#cloud-config
users:
  - default
  - name: worker
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    #ssh_import_id:
    #  - gh:a-h # Use the SSH key from github.com for user a-h.
    ssh_authorized_keys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC4ZYYVVw4dsNtzOnBCTXbjuRqOowMOvP3zetYXeE5i+2Strt1K4vAw37nrIwx3JsSghxq1Qrg9ra0aFJbwtaN3119RR0TaHpatc6TJCtwuXwkIGtwHf0/HTt6AH8WOt7RFCNbH3FuoJ1oOqx6LZOqdhUjAlWRDv6XH9aTnsEk8zf+1m30SQrG8Vcclj1CTFMAa+o6BgGdHoextOhGMlTx8ESAlgIXCo+dIVjANE2qbfAg0XL0+BpwlRDJt5OcgzrILXZ1jSIYRW4eg/JBcDW/WqorEummxhB26Y6R0jeswRF3DOQhU2fAhbsCWdairLam42rFGlKfWyTbgjRXl/BNR 

runcmd:
  - curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install --no-confirm
  - echo "trusted-users = root worker" >> /etc/nix/nix.conf
  - echo "flake-registry = /etc/nix/flake-registry.json" >> /etc/nix/nix.conf
  - # Restart daemon after config change.
  - sudo systemctl restart nix-daemon
  - mkdir /flakes
  - chown worker:worker /flakes
  - iptables -t filter -I OUTPUT 1 -m state --state NEW -j DROP

